<a href="https://colab.research.google.com/github/namoshi/ml_intro/blob/master/ball_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 重回帰分析によるボール投げの予測モデルの学習

握力，体重，身長からボール投げの記録を予測する


In [4]:
import numpy as np
import pandas.util.testing as tm
import statsmodels.api as sm


ボール投げのデータの読み込み（サンプル数：15，握力，体重，身長，ボール投げの記録）

In [5]:
# Read Data
data = np.loadtxt("https://raw.githubusercontent.com/namoshi/ml_intro/master/ball.dat", comments="#")

print('data\n', data)

x = data[:,1:]

y = data[:,0]

print('x\n', x)
print('y\n', y)

X = sm.add_constant(x)
print('X\n', X)


data
 [[ 22.  28. 146.  34.]
 [ 36.  46. 169.  57.]
 [ 24.  39. 160.  48.]
 [ 22.  25. 156.  38.]
 [ 27.  34. 161.  47.]
 [ 29.  29. 168.  50.]
 [ 26.  38. 154.  54.]
 [ 23.  23. 153.  40.]
 [ 31.  42. 160.  62.]
 [ 24.  27. 152.  39.]
 [ 23.  35. 155.  46.]
 [ 27.  39. 154.  54.]
 [ 31.  38. 157.  57.]
 [ 25.  32. 162.  53.]
 [ 23.  25. 142.  32.]]
x
 [[ 28. 146.  34.]
 [ 46. 169.  57.]
 [ 39. 160.  48.]
 [ 25. 156.  38.]
 [ 34. 161.  47.]
 [ 29. 168.  50.]
 [ 38. 154.  54.]
 [ 23. 153.  40.]
 [ 42. 160.  62.]
 [ 27. 152.  39.]
 [ 35. 155.  46.]
 [ 39. 154.  54.]
 [ 38. 157.  57.]
 [ 32. 162.  53.]
 [ 25. 142.  32.]]
y
 [22. 36. 24. 22. 27. 29. 26. 23. 31. 24. 23. 27. 31. 25. 23.]
X
 [[  1.  28. 146.  34.]
 [  1.  46. 169.  57.]
 [  1.  39. 160.  48.]
 [  1.  25. 156.  38.]
 [  1.  34. 161.  47.]
 [  1.  29. 168.  50.]
 [  1.  38. 154.  54.]
 [  1.  23. 153.  40.]
 [  1.  42. 160.  62.]
 [  1.  27. 152.  39.]
 [  1.  35. 155.  46.]
 [  1.  39. 154.  54.]
 [  1.  38. 157.  57.]
 [  1. 

線形回帰モデルの学習（OLSを利用）

In [6]:
model = sm.OLS(y, X)

results = model.fit()
results.summary()

/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.691
Model:                            OLS   Adj. R-squared:                  0.607
Method:                 Least Squares   F-statistic:                     8.213
Date:                Sat, 25 Jul 2020   Prob (F-statistic):            0.00377
Time:                        01:27:50   Log-Likelihood:                -32.890
No. Observations:                  15   AIC:                             73.78
Df Residuals:                      11   BIC:                             76.61
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -13.2173     17.604     -0.751      0.469     -51.963      25.528
x1             0.2014      0.184      1.093      0.298      -0.204       0.607
x2             0.1710      0.132      1.300      0.220      -0.119       0.461
x3             0.1249      0.167      0.750      0.469      -0.242       0.492
==============================================================================
Omnibus:                        0.111   Durbin-Watson:                   2.665
Prob(Omnibus):                  0.946   Jarque-Bera (JB):                0.333
Skew:                          -0.062   Prob(JB):                        0.847
Kurtosis:                       2.281   Cond. No.                     4.50e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.5e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""