In [8]:
import numpy as np

iris = np.loadtxt('iris.dat')
nr, nc = iris.shape

print(nr, nc)

150 4


In [11]:
# feature vectors of each class
#
#print(iris_data)

mean_iris = np.mean(iris, axis=0)
std_iris = np.std(iris, axis=0)

niris = (iris - mean_iris)/ std_iris

print(mean_iris)
print(std_iris)
print(niris)

mean_niris = np.mean(niris, axis=0)
std_niris = np.std(niris, axis=0)

print(mean_niris)
print(std_niris)

[5.85       3.05733333 3.758      1.19933333]
[0.82613558 0.43441097 1.75940407 0.75969263]
[[-9.07841299e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14993231e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.39202333e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.51306883e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-9.07841299e-01  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.44704779e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.51306883e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02888681e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.75515984e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14993231e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.44704779e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.27097782e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.27097782e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87620535e+00 -1.31979479e-01 -1.

In [15]:
np.savetxt('niris.dat', niris, delimiter=' ')